# Site settings
name: 永恒的空间
email: 916016807@qq.com
author: linxc
url: http://www.hifreud.com
resume_site: https://github.com/anheihuashi/my-blog/
github: https://github.com/anheihuashi/my-blog
baseurl: "/my-blog"
description: Actually, less is more!
meta_description: lxc;个人博客;永无止尽
motto: It's our wits that make us men.
banner: 学习可以使你摆脱迷惘

#permalink: /:categories/:year/:month/:day/:title/
permalink: /:year/:month/:day/:title/
paginate: 10

exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile']

github_username: anheihuashi
highlighter: Pygments

# Build settings
markdown: kramdown

baidu_analysis: 94be4b0f9fc5d94cc0d0415ea6761ae9

FB:
  comments :
    provider : duoshuo
    duoshuo:
        short_name : luoyan35714
    disqus :
        short_name : freudkang
    # facebook :
    #   appid : 123
    #   num_posts: 5
    #   width: 580
    #   colorscheme: light

gems: [jekyll-paginate]